main: penowl.plugin.migs.InvCtmr
name: MIGS
version: 1.3
author: PenguinOwl
description: An Ecomomy plugin that allows player to make easy shops from signs and chests
depends: [Vault]
commands:
  migs:
    description: The main MIGS command.
    usage: /<command> [reload]
    permission: migs.reload
    permission-message: You don't have <permission>